---
title: "金融统计基础第一次作业"
author: 
  - 王程航
  - 王泽浩
  - 张申铎
  - 闫雨菲
output: 
  pdf_document: 
    latex_engine: xelatex
    include:
      in_header: header.tex
    fig_caption: yes
    number_sections: yes
    toc: yes
classoption: "hyperref,"
documentclass: ctexart
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rticles)
```

# 需要使用到的包

```{r,message=FALSE}
library(fGarch)
library(ggplot2)
library(forecast)
library(tseries)
library(scales)
library(plyr)
library(TTR)
set.seed(2020)
```

# 数据特征

```{r}
daily_2008 <- read.csv("../Data/SP500/08年每日.csv")
SPY <- ts(daily_2008$收盘, frequency = 251, start = c(2008, 1))
Diffrence_of_SPY <- ts(diff(SPY), 
                       frequency = 251, start = c(2008, 1))
par(mfrow=c(2,1))
plot(SPY)
plot(Diffrence_of_SPY)
```

# 建模分析


## ARIMA模型

### 定阶

```{r}
cprice <- diff(daily_2008$收盘)
par(mfrow=c(2,1))
acf(cprice)
pacf(cprice)
```

### ARIMA1

#### 模型

```{r}
m2 <- arima(cprice, order = c(3, 0, 0), 
            seasonal = list(order = c(2, 0, 0), period = 5), 
            include.mean = F)
m2
```

#### 图像

```{r}
plot(m2)
checkresiduals(m2)
```

#### 预测

```{r}
plot(forecast(m2,h=10),xlim=c(3000,3090))
```

### ARIMA2

#### 模型

```{r}
m3 <- arima(cprice, seasonal = list(order = c(2, 0, 0), period = 5), include.mean = F)
summary(m3)
```

#### 图像

```{r}
plot(m3)
checkresiduals(m3)
```

#### 预测

```{r}
plot(forecast(m3,h=10),xlim=c(3000,3090))
```

## ARMA+GARCH模型

### 定阶

```{r}
adjcp <- cprice[11:3081] + 0.0817 * cprice[6:3076] - 0.0667 * cprice[1:3071]
par(mfrow=c(2,1))
acf(adjcp)
pacf(adjcp)
```

### 第一个模型

#### 模型

```{r}
m4 <- garchFit(~arma(3, 0) + garch(1, 1), data = adjcp, trace = F, include.mean = F)
summary(m4)
```

#### 图像

```{r}
plot(m4,which=1)
plot(m4,which=13)
```

#### 预测

BUG

### 第二个模型

#### 模型

```{r}
m5 <- garchFit(~arma(3, 0) + garch(1, 1), data = adjcp, trace = F, include.mean = F, cond.dist = "std")
summary(m5)
```

#### 图像

```{r}
plot(m5,which=1)
plot(m5,which=13)
```

#### 预测

BUG

### 第三个模型

#### 模型

```{r}
m6 <- garchFit(~arma(1, 0) + garch(1, 1), data = adjcp, trace = F, include.mean = F, cond.dist = "sstd")
summary(m6)
```

#### 图像

```{r}
plot(m6,which=1)
plot(m6,which=13)
```

#### 预测

```{r}
predict(m6,n.ahead=30,plot=TRUE)
```

### 指数模型


```{r}
monthly_2008 <- read.csv("../Data/SP500/08年每月.csv")
Monthly_Price<-monthly_2008$收盘
Monthly_Pricets<-ts(Monthly_Price,frequency = 12,start=c(2008,1))
fit_ets<-ets(Monthly_Pricets)
fit_ets
```

#### 图像

```{r}
plot(fit_ets)
```

#### 预测 

```{r}
plot(forecast(fit_ets),xlab="Time",flty=2)
```


```{r}
accuracy(fit_ets)
```


